export enum LotteriesProduct {
    'None',
    'TattsLotto',
    'OzLotto',
    'Powerball',
    'Super66',
    'Pools',
    'MonWedLotto',
    'LuckyLotteries2',
    'LuckyLotteries5',
    'LottoStrike',
    'WedLotto',
    'Keno',
    'CoinToss',
    'SetForLife',
    'MultiProduct' = 15,
    'InstantScratchIts',
    'TwoDollarCasket',
    'BonusDraws'
}
