export enum LotteriesProduct {
    None = 'None',
    TattsLotto = 'TattsLotto',
    OzLotto = 'OzLotto',
    Powerball = 'Powerball',
    Super66 = 'Super66',
    Pools = 'Pools',
    MonWedLotto = 'MonWedLotto',
    LuckyLotteries2 = 'LuckyLotteries2',
    LuckyLotteries5 = 'LuckyLotteries5',
    LottoStrike = 'LottoStrike',
    WedLotto = 'WedLotto',
    Keno = 'Keno',
    CoinToss = 'CoinToss',
    SetForLife = 'SetForLife744',
    MultiProduct = 'MultiProduct',
    InstantScratchIts = 'InstantScratchIts',
    TwoDollarCasket = 'TwoDollarCasket',
    BonusDraws = 'BonusDraws'
}
